/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RbacAuditRouteImport } from './routes/rbac-audit'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemIndexRouteImport } from './routes/system/index'
import { Route as PipelinesIndexRouteImport } from './routes/pipelines/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as BuildsIndexRouteImport } from './routes/builds/index'
import { Route as ApprovalsIndexRouteImport } from './routes/approvals/index'
import { Route as WorkersEventsRouteImport } from './routes/workers.events'
import { Route as PipelinesValidateRouteImport } from './routes/pipelines/validate'
import { Route as PipelinesPipelineIdRouteImport } from './routes/pipelines/$pipelineId'
import { Route as OnboardingManualRouteImport } from './routes/onboarding_.manual'
import { Route as LoginCallbackRouteImport } from './routes/login.callback'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as BuildsCompareRouteImport } from './routes/builds/compare'
import { Route as BuildsBuildIdRouteImport } from './routes/builds/$buildId'
import { Route as IntegrationsPulsarIndexRouteImport } from './routes/integrations.pulsar.index'
import { Route as IntegrationsGithubIndexRouteImport } from './routes/integrations.github.index'
import { Route as IntegrationsGithubInstallIdRouteImport } from './routes/integrations.github.$installId'
import { Route as BuildsBuildIdCompareOtherRouteImport } from './routes/builds/$buildId_.compare.$other'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RbacAuditRoute = RbacAuditRouteImport.update({
  id: '/rbac-audit',
  path: '/rbac-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsIndexRoute = ApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersEventsRoute = WorkersEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => WorkersRoute,
} as any)
const PipelinesValidateRoute = PipelinesValidateRouteImport.update({
  id: '/pipelines/validate',
  path: '/pipelines/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesPipelineIdRoute = PipelinesPipelineIdRouteImport.update({
  id: '/pipelines/$pipelineId',
  path: '/pipelines/$pipelineId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingManualRoute = OnboardingManualRouteImport.update({
  id: '/onboarding_/manual',
  path: '/onboarding/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => LoginRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsCompareRoute = BuildsCompareRouteImport.update({
  id: '/builds/compare',
  path: '/builds/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsBuildIdRoute = BuildsBuildIdRouteImport.update({
  id: '/builds/$buildId',
  path: '/builds/$buildId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsPulsarIndexRoute = IntegrationsPulsarIndexRouteImport.update({
  id: '/integrations/pulsar/',
  path: '/integrations/pulsar/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsGithubIndexRoute = IntegrationsGithubIndexRouteImport.update({
  id: '/integrations/github/',
  path: '/integrations/github/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsGithubInstallIdRoute =
  IntegrationsGithubInstallIdRouteImport.update({
    id: '/integrations/github/$installId',
    path: '/integrations/github/$installId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BuildsBuildIdCompareOtherRoute =
  BuildsBuildIdCompareOtherRouteImport.update({
    id: '/builds/$buildId_/compare/$other',
    path: '/builds/$buildId/compare/$other',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/rbac-audit': typeof RbacAuditRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/workers': typeof WorkersRouteWithChildren
  '/builds/$buildId': typeof BuildsBuildIdRoute
  '/builds/compare': typeof BuildsCompareRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/onboarding/manual': typeof OnboardingManualRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/pipelines/validate': typeof PipelinesValidateRoute
  '/workers/events': typeof WorkersEventsRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/builds/': typeof BuildsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/system/': typeof SystemIndexRoute
  '/integrations/github/$installId': typeof IntegrationsGithubInstallIdRoute
  '/integrations/github/': typeof IntegrationsGithubIndexRoute
  '/integrations/pulsar/': typeof IntegrationsPulsarIndexRoute
  '/builds/$buildId/compare/$other': typeof BuildsBuildIdCompareOtherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/rbac-audit': typeof RbacAuditRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/workers': typeof WorkersRouteWithChildren
  '/builds/$buildId': typeof BuildsBuildIdRoute
  '/builds/compare': typeof BuildsCompareRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/onboarding/manual': typeof OnboardingManualRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/pipelines/validate': typeof PipelinesValidateRoute
  '/workers/events': typeof WorkersEventsRoute
  '/approvals': typeof ApprovalsIndexRoute
  '/builds': typeof BuildsIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/pipelines': typeof PipelinesIndexRoute
  '/system': typeof SystemIndexRoute
  '/integrations/github/$installId': typeof IntegrationsGithubInstallIdRoute
  '/integrations/github': typeof IntegrationsGithubIndexRoute
  '/integrations/pulsar': typeof IntegrationsPulsarIndexRoute
  '/builds/$buildId/compare/$other': typeof BuildsBuildIdCompareOtherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/rbac-audit': typeof RbacAuditRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/workers': typeof WorkersRouteWithChildren
  '/builds/$buildId': typeof BuildsBuildIdRoute
  '/builds/compare': typeof BuildsCompareRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/login/callback': typeof LoginCallbackRoute
  '/onboarding_/manual': typeof OnboardingManualRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdRoute
  '/pipelines/validate': typeof PipelinesValidateRoute
  '/workers/events': typeof WorkersEventsRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/builds/': typeof BuildsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/system/': typeof SystemIndexRoute
  '/integrations/github/$installId': typeof IntegrationsGithubInstallIdRoute
  '/integrations/github/': typeof IntegrationsGithubIndexRoute
  '/integrations/pulsar/': typeof IntegrationsPulsarIndexRoute
  '/builds/$buildId_/compare/$other': typeof BuildsBuildIdCompareOtherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/queue'
    | '/rbac-audit'
    | '/settings'
    | '/users'
    | '/workers'
    | '/builds/$buildId'
    | '/builds/compare'
    | '/jobs/$jobId'
    | '/login/callback'
    | '/onboarding/manual'
    | '/pipelines/$pipelineId'
    | '/pipelines/validate'
    | '/workers/events'
    | '/approvals/'
    | '/builds/'
    | '/integrations/'
    | '/jobs/'
    | '/pipelines/'
    | '/system/'
    | '/integrations/github/$installId'
    | '/integrations/github/'
    | '/integrations/pulsar/'
    | '/builds/$buildId/compare/$other'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/queue'
    | '/rbac-audit'
    | '/settings'
    | '/users'
    | '/workers'
    | '/builds/$buildId'
    | '/builds/compare'
    | '/jobs/$jobId'
    | '/login/callback'
    | '/onboarding/manual'
    | '/pipelines/$pipelineId'
    | '/pipelines/validate'
    | '/workers/events'
    | '/approvals'
    | '/builds'
    | '/integrations'
    | '/jobs'
    | '/pipelines'
    | '/system'
    | '/integrations/github/$installId'
    | '/integrations/github'
    | '/integrations/pulsar'
    | '/builds/$buildId/compare/$other'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/queue'
    | '/rbac-audit'
    | '/settings'
    | '/users'
    | '/workers'
    | '/builds/$buildId'
    | '/builds/compare'
    | '/jobs/$jobId'
    | '/login/callback'
    | '/onboarding_/manual'
    | '/pipelines/$pipelineId'
    | '/pipelines/validate'
    | '/workers/events'
    | '/approvals/'
    | '/builds/'
    | '/integrations/'
    | '/jobs/'
    | '/pipelines/'
    | '/system/'
    | '/integrations/github/$installId'
    | '/integrations/github/'
    | '/integrations/pulsar/'
    | '/builds/$buildId_/compare/$other'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  LoginRoute: typeof LoginRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  QueueRoute: typeof QueueRoute
  RbacAuditRoute: typeof RbacAuditRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  WorkersRoute: typeof WorkersRouteWithChildren
  BuildsBuildIdRoute: typeof BuildsBuildIdRoute
  BuildsCompareRoute: typeof BuildsCompareRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  OnboardingManualRoute: typeof OnboardingManualRoute
  PipelinesPipelineIdRoute: typeof PipelinesPipelineIdRoute
  PipelinesValidateRoute: typeof PipelinesValidateRoute
  ApprovalsIndexRoute: typeof ApprovalsIndexRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
  SystemIndexRoute: typeof SystemIndexRoute
  IntegrationsGithubInstallIdRoute: typeof IntegrationsGithubInstallIdRoute
  IntegrationsGithubIndexRoute: typeof IntegrationsGithubIndexRoute
  IntegrationsPulsarIndexRoute: typeof IntegrationsPulsarIndexRoute
  BuildsBuildIdCompareOtherRoute: typeof BuildsBuildIdCompareOtherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rbac-audit': {
      id: '/rbac-audit'
      path: '/rbac-audit'
      fullPath: '/rbac-audit'
      preLoaderRoute: typeof RbacAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/': {
      id: '/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/': {
      id: '/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof ApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/events': {
      id: '/workers/events'
      path: '/events'
      fullPath: '/workers/events'
      preLoaderRoute: typeof WorkersEventsRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/pipelines/validate': {
      id: '/pipelines/validate'
      path: '/pipelines/validate'
      fullPath: '/pipelines/validate'
      preLoaderRoute: typeof PipelinesValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$pipelineId': {
      id: '/pipelines/$pipelineId'
      path: '/pipelines/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof PipelinesPipelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding_/manual': {
      id: '/onboarding_/manual'
      path: '/onboarding/manual'
      fullPath: '/onboarding/manual'
      preLoaderRoute: typeof OnboardingManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/compare': {
      id: '/builds/compare'
      path: '/builds/compare'
      fullPath: '/builds/compare'
      preLoaderRoute: typeof BuildsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/$buildId': {
      id: '/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/builds/$buildId'
      preLoaderRoute: typeof BuildsBuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/pulsar/': {
      id: '/integrations/pulsar/'
      path: '/integrations/pulsar'
      fullPath: '/integrations/pulsar/'
      preLoaderRoute: typeof IntegrationsPulsarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/github/': {
      id: '/integrations/github/'
      path: '/integrations/github'
      fullPath: '/integrations/github/'
      preLoaderRoute: typeof IntegrationsGithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/github/$installId': {
      id: '/integrations/github/$installId'
      path: '/integrations/github/$installId'
      fullPath: '/integrations/github/$installId'
      preLoaderRoute: typeof IntegrationsGithubInstallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/$buildId_/compare/$other': {
      id: '/builds/$buildId_/compare/$other'
      path: '/builds/$buildId/compare/$other'
      fullPath: '/builds/$buildId/compare/$other'
      preLoaderRoute: typeof BuildsBuildIdCompareOtherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginCallbackRoute: typeof LoginCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCallbackRoute: LoginCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface WorkersRouteChildren {
  WorkersEventsRoute: typeof WorkersEventsRoute
}

const WorkersRouteChildren: WorkersRouteChildren = {
  WorkersEventsRoute: WorkersEventsRoute,
}

const WorkersRouteWithChildren =
  WorkersRoute._addFileChildren(WorkersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  LoginRoute: LoginRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  QueueRoute: QueueRoute,
  RbacAuditRoute: RbacAuditRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  WorkersRoute: WorkersRouteWithChildren,
  BuildsBuildIdRoute: BuildsBuildIdRoute,
  BuildsCompareRoute: BuildsCompareRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  OnboardingManualRoute: OnboardingManualRoute,
  PipelinesPipelineIdRoute: PipelinesPipelineIdRoute,
  PipelinesValidateRoute: PipelinesValidateRoute,
  ApprovalsIndexRoute: ApprovalsIndexRoute,
  BuildsIndexRoute: BuildsIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
  SystemIndexRoute: SystemIndexRoute,
  IntegrationsGithubInstallIdRoute: IntegrationsGithubInstallIdRoute,
  IntegrationsGithubIndexRoute: IntegrationsGithubIndexRoute,
  IntegrationsPulsarIndexRoute: IntegrationsPulsarIndexRoute,
  BuildsBuildIdCompareOtherRoute: BuildsBuildIdCompareOtherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
