<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Titan daily digest — {{dayLabel}}</title>
<style>
  body { font-family: -apple-system, system-ui, "Segoe UI", sans-serif; color: #1a1a1a; background: #fafafa; margin: 0; padding: 24px; }
  .card { max-width: 720px; margin: 0 auto; background: #fff; border: 1px solid #e5e5e5; border-radius: 8px; padding: 24px; }
  h1 { font-size: 18px; font-weight: 600; margin: 0 0 4px; }
  .sub { color: #6b7280; font-size: 13px; margin: 0 0 20px; }
  h2 { font-size: 14px; font-weight: 600; margin: 24px 0 8px; color: #374151; text-transform: uppercase; letter-spacing: 0.04em; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; font-weight: 500; color: #6b7280; border-bottom: 1px solid #e5e5e5; padding: 8px 12px; }
  td { padding: 8px 12px; border-bottom: 1px solid #f3f4f6; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; }
  .muted { color: #9ca3af; font-style: italic; text-align: center; }
  .kpi { display: inline-block; margin-right: 24px; font-size: 13px; color: #374151; }
  .kpi strong { display: block; font-size: 22px; font-weight: 600; color: #111827; }
  .footer { color: #9ca3af; font-size: 11px; margin-top: 24px; text-align: center; }
</style>
</head>
<body>
<div class="card">
  <h1>Titan daily digest — {{dayLabel}}</h1>
  <p class="sub">Window: {{windowStart}} → {{windowEnd}}</p>

  <div>
    <span class="kpi"><strong>{{totalBuilds}}</strong>builds</span>
    <span class="kpi"><strong>{{totalFailures}}</strong>failures</span>
    <span class="kpi"><strong>{{failingCount}}</strong>jobs affected</span>
  </div>

  <h2>Failing jobs</h2>
  <table>
    <thead><tr><th>Job</th><th class="num">Failures</th><th class="num">Total</th><th>Last failure</th></tr></thead>
    <tbody>
{{failingRows}}
    </tbody>
  </table>

  <h2>Top 5 longest builds</h2>
  <table>
    <thead><tr><th>Build</th><th>Status</th><th class="num">Duration</th><th>Finished</th></tr></thead>
    <tbody>
{{longestRows}}
    </tbody>
  </table>

  <p class="footer">Generated by Titan. Reply to this email is not monitored.</p>
</div>
</body>
</html>
