#!/usr/bin/env bash
# check-routetree-fresh.sh — TanStack routeTree.gen.ts freshness guard (#1155, #1159).
#
# Why this exists:
#   titan-ui/src/routeTree.gen.ts is a GENERATED file (TanStack Router's vite
#   plugin writes it during `pnpm build`). It is committed to git so editors /
#   tsc resolve routes without a build. The failure mode in #1155: a route was
#   added/changed but the regenerated routeTree.gen.ts was NOT re-committed.
#   `tsc` and `vite build` both pass against the STALE committed file, so the
#   drift is invisible pre-merge — it only bites at runtime when the live route
#   table disagrees with the source routes. Nothing caught it before merge.
#
#   This script closes that gap. It compares the COMMITTED routeTree.gen.ts
#   against a freshly-regenerated one and fails the PR gate (`task ci:verify` →
#   `verify:routetree`) if they differ, with a clear remediation message.
#
# Two modes (the two-file mode is the pure, unit-testable core):
#
#   1. Two-file compare (used by the unit tests):
#        check-routetree-fresh.sh <committed-file> <fresh-file>
#      Diffs the two files. Identical => exit 0. Different => exit 1 + message.
#
#   2. Git mode (used by the gate, after a build has regenerated the file):
#        check-routetree-fresh.sh --git <path-relative-to-repo>
#      Compares the working-tree file (freshly regenerated by the preceding
#      `pnpm build` in `verify:ui`) against its committed (HEAD) version.
#      Identical => exit 0. Drifted => exit 1 + message.
#
# Exit codes:
#   0 — routeTree.gen.ts is fresh (matches regenerated output)
#   1 — routeTree.gen.ts is STALE (differs) — names the file + remediation
#   2 — usage / config error
set -euo pipefail

STALE_MSG() {
  local path="$1"
  echo "[routetree] FAIL: $path is stale." >&2
  echo "[routetree] The committed route tree does not match the regenerated one (see #1155)." >&2
  echo "[routetree] Fix: run \`pnpm -C titan-ui build\` and commit the updated src/routeTree.gen.ts." >&2
}

usage() {
  echo "usage: check-routetree-fresh.sh <committed-file> <fresh-file>" >&2
  echo "       check-routetree-fresh.sh --git <path-relative-to-repo>" >&2
  exit 2
}

if [ "$#" -eq 0 ]; then
  usage
fi

if [ "$1" = "--git" ]; then
  # ── Git mode ────────────────────────────────────────────────────────────
  [ "$#" -eq 2 ] || usage
  REL="$2"
  # REPO_ROOT defaults to the script's ../.. (the repo it ships in). Tests
  # override it (ROUTETREE_REPO_ROOT) to point the git compare at a throwaway
  # repo, so the --git path — the one the gate actually runs — is testable in
  # isolation rather than only against the live tree.
  if [ -n "${ROUTETREE_REPO_ROOT:-}" ]; then
    REPO_ROOT="$(cd "$ROUTETREE_REPO_ROOT" && pwd)"
  else
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
  fi
  WORKTREE_FILE="$REPO_ROOT/$REL"

  if [ ! -f "$WORKTREE_FILE" ]; then
    echo "[routetree] generated file missing in working tree: $WORKTREE_FILE" >&2
    echo "[routetree] expected \`pnpm -C titan-ui build\` to have produced it first." >&2
    exit 2
  fi

  # Compare the working-tree (freshly built) file against its committed HEAD
  # blob. We pin the comparison to HEAD explicitly (not the bare `git diff`,
  # which compares against the *index*): if routeTree.gen.ts has been staged
  # mid-workflow, a bare diff would compare the regenerated file against the
  # staged blob and a stale *committed* file could pass silently. `--quiet`
  # exits non-zero iff the working tree differs from HEAD.
  if git -C "$REPO_ROOT" diff --quiet HEAD -- "$REL"; then
    echo "[routetree] OK: $REL matches the regenerated output (fresh)."
    exit 0
  fi
  STALE_MSG "$REL"
  echo "[routetree] --- diff (committed vs regenerated) ---" >&2
  git -C "$REPO_ROOT" --no-pager diff HEAD -- "$REL" | head -n 40 >&2 || true
  exit 1
fi

# ── Two-file compare mode ───────────────────────────────────────────────────
[ "$#" -eq 2 ] || usage
COMMITTED="$1"
FRESH="$2"

for f in "$COMMITTED" "$FRESH"; do
  if [ ! -f "$f" ]; then
    echo "[routetree] file not found: $f" >&2
    exit 2
  fi
done

if diff -q "$COMMITTED" "$FRESH" >/dev/null 2>&1; then
  echo "[routetree] OK: routeTree is fresh (committed matches regenerated)."
  exit 0
fi

STALE_MSG "$COMMITTED"
echo "[routetree] --- diff (committed vs regenerated) ---" >&2
diff "$COMMITTED" "$FRESH" | head -n 40 >&2 || true
exit 1
