-- V25__agent_events.sql — worker join/leave event log for the Home activity timeline (closes #714).
--
-- Why a separate event table (not derived from titan.agents):
--   titan.agents holds CURRENT state only; once an agent is deleted or re-registers,
--   the prior "joined" moment is gone. The Home timeline needs the lifecycle
--   stream — a join is not the same fact as the current row.
--
-- Scope (T58 simpler scope): only JOINED and LEFT for now. HEARTBEAT_LOST is reserved
--   in the CHECK below as a follow-up once a stale-agent reaper exists; the column
--   widens additively without a migration when we ship it.
--
-- Foreign key: agent_id references titan.agents(agent_id) (VARCHAR(128) natural key,
--   NOT a BIGINT — the brief's BIGSERIAL FK was based on an incorrect read of the
--   agents schema). ON DELETE CASCADE: if an agent row is hard-deleted the lifecycle
--   trail goes with it (we keep events only for currently-known agents; the timeline
--   joins to titan.agents.display_name).
--
-- meta column: short opaque text ('{}' default). Stored as VARCHAR (not JSONB) so the
--   same DDL runs on H2 and Postgres without dialect-specific casts — matches the
--   capabilities_json convention from V1__init.
CREATE TABLE titan.agent_events (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    VARCHAR(128)  NOT NULL REFERENCES titan.agents(agent_id) ON DELETE CASCADE,
    event_type  VARCHAR(32)   NOT NULL
                CHECK (event_type IN ('JOINED','LEFT')),
    occurred_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    meta        VARCHAR       NOT NULL DEFAULT '{}'
);

-- Newest-first listing is the dominant query (timeline shows the latest N events).
CREATE INDEX idx_agent_events_occurred_at ON titan.agent_events (occurred_at DESC);

-- Common access pattern: "events for this agent" (future per-agent activity sub-pane).
CREATE INDEX idx_agent_events_agent_id ON titan.agent_events (agent_id);
