-- V37__group_role_mapping.sql
-- Issue #1136 — SSO group -> Titan role mapping (per-org).
--
-- A row says: "every authenticated user whose OIDC `groups` claim contains
-- `group_path` (full-path form, e.g. /acme/platform-admins) holds Titan role
-- `role` on org `org_id`."
--
-- v1 roles (per CONSTITUTION): ADMIN, MAINTAINER, DEVELOPER, VIEWER. The
-- enum is enforced by application code (GroupMappingValidator) so that a
-- future role addition is a one-line code change, not a CHECK constraint
-- migration.
--
-- (org_id, group_path) is the natural key — a single group cannot grant
-- two different roles on the same org (highest-role-wins is computed at
-- read time across the whole claim set, not by stacking rows here).
--
-- Backfill: nothing to backfill. Existing orgs start with zero mappings;
-- admins populate the table via the new /api/v1/orgs/{id}/sso/mappings
-- endpoints. Until rows exist, OIDC users continue to land on whatever
-- role they had under the pre-#1136 path (VIEWER by default-deny).

CREATE TABLE IF NOT EXISTS titan.group_role_mapping (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id      VARCHAR(128) NOT NULL,
  group_path  VARCHAR(512) NOT NULL,
  role        VARCHAR(64)  NOT NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_group_role_mapping_org_group UNIQUE (org_id, group_path)
);

CREATE INDEX IF NOT EXISTS idx_group_role_mapping_org
  ON titan.group_role_mapping (org_id);

CREATE INDEX IF NOT EXISTS idx_group_role_mapping_group
  ON titan.group_role_mapping (group_path);
