-- V39__scm_webhook_event.sql
-- Issue #1129 — durable webhook ingestion with retry + dedupe.
--
-- The hot-path table for raw webhook deliveries. Distinct from V36's scm_event_seen:
--
--   scm_event_seen       — dispatch-side dedupe key (single row per (provider, event_id)),
--                          inserted only AFTER the handler decides to enqueue a build. It
--                          guards the build pipeline from duplicate dispatch.
--
--   scm_webhook_event    — ingestion-side durable log. Every webhook POST that passes
--                          signature verification is INSERTED here BEFORE the handler runs,
--                          keyed by (provider, delivery_id). If the handler crashes — JVM
--                          OOM, DB hiccup, a downstream call timeout — the row remains in
--                          status='PENDING' and a timer-driven sweeper retries it. On
--                          terminal failure the row is marked 'FAILED' with the last error
--                          and surfaced to operators.
--
-- Why two tables instead of one wider row on scm_event_seen: ingestion and dispatch are
-- different lifecycle concerns. The ingestion row may exist for an event we ultimately
-- decide not to dispatch (no matching job, wrong ref, etc.) — that's still a valid
-- "we received it" record. Conflating the two would force every reconcile insert to also
-- carry a raw body it doesn't have.
--
-- Forward-only. Safe to re-run via IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS titan.scm_webhook_event (
  id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider        VARCHAR(32)  NOT NULL,
  delivery_id     VARCHAR(255) NOT NULL,
  event_type      VARCHAR(64)  NOT NULL,
  received_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- PENDING | PROCESSED | FAILED. PENDING rows are picked up by the timer-driven
  -- retry worker; PROCESSED rows are kept for an operator-visible delivery log
  -- (TTL'd by an out-of-band sweep); FAILED rows are surfaced for operator triage.
  status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
  attempts        INT          NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMP,
  last_error      VARCHAR(2048),
  payload         TEXT         NOT NULL,
  signature       VARCHAR(255),
  CONSTRAINT uq_scm_webhook_event_provider_delivery UNIQUE (provider, delivery_id)
);

-- Sweeper hot path: claim PENDING rows whose retry time is past due.
CREATE INDEX IF NOT EXISTS idx_scm_webhook_event_due
  ON titan.scm_webhook_event (status, next_attempt_at);

-- Operator-facing list (newest-first) for the failed-delivery surface.
CREATE INDEX IF NOT EXISTS idx_scm_webhook_event_received_at
  ON titan.scm_webhook_event (received_at);
