package io.adaptiq.titan.job;

import edu.umd.cs.findbugs.annotations.Nullable;

/**
 * Input record for {@link JobService#create(NewJobRequest)}: the minimal set of fields a caller
 * must supply to materialise a new {@code titan.jobs} row. {@code createdAt}/{@code updatedAt} are
 * assigned by the database column defaults; {@code id} is generated by the SQL identity.
 */
public record NewJobRequest(
    String fullName,
    @Nullable String displayName,
    @Nullable String folderPath,
    String pipelineScript,
    String configJson,
    @Nullable String createdBy,
    boolean enabled) {}
