#!/usr/bin/env bash
# Adversarial unit test for dev/sprint-loop/check-routetree-fresh.sh (#1155, #1159).
#
# Acceptance criterion under test:
#   The routeTree freshness guard must turn a stale committed
#   titan-ui/src/routeTree.gen.ts into a RED PR gate (exit 1, clear "run
#   `pnpm -C titan-ui build` and commit" message), not a runtime route-table
#   drift. #1155 shipped a stale generated file: tsc/vite both passed against
#   it, so the drift was invisible until runtime. These tests pin the pure
#   two-file compare core: identical => 0, drifted => 1 with the remediation
#   message, missing file => loud config error.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
SCRIPT="$REPO_ROOT/dev/sprint-loop/check-routetree-fresh.sh"

if [ ! -f "$SCRIPT" ]; then
  echo "FAIL: $SCRIPT missing" >&2
  exit 1
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

routetree_a='// generated by TanStack Router
export const routeTree = rootRoute.addChildren([HomeRoute, QueueRoute])'

routetree_drifted='// generated by TanStack Router
export const routeTree = rootRoute.addChildren([HomeRoute, QueueRoute, NewlyAddedRoute])'

# ── Case 1: committed == regenerated → fresh, exit 0 ─────────────────────────
printf '%s\n' "$routetree_a" > "$TMP/committed.ts"
printf '%s\n' "$routetree_a" > "$TMP/fresh.ts"
set +e
out=$(bash "$SCRIPT" "$TMP/committed.ts" "$TMP/fresh.ts" 2>&1); rc=$?
set -e
if [ "$rc" -ne 0 ]; then echo "FAIL: identical files should exit 0, got $rc: $out" >&2; exit 1; fi
echo "ok: committed matches regenerated → exit 0 (fresh)"

# ── Case 2: ADVERSARIAL — committed is STALE (route added) → exit 1 ──────────
# The literal #1155 shape: a route was added, the generated file regenerated
# differently, but the stale one was committed.
printf '%s\n' "$routetree_a" > "$TMP/committed.ts"
printf '%s\n' "$routetree_drifted" > "$TMP/fresh.ts"
set +e
out=$(bash "$SCRIPT" "$TMP/committed.ts" "$TMP/fresh.ts" 2>&1); rc=$?
set -e
if [ "$rc" -ne 1 ]; then echo "FAIL: stale file should exit 1, got $rc" >&2; exit 1; fi
if ! printf '%s' "$out" | grep -q "stale"; then
  echo "FAIL: output must say the file is stale. got: $out" >&2; exit 1
fi
if ! printf '%s' "$out" | grep -q "pnpm -C titan-ui build"; then
  echo "FAIL: output must give the remediation command. got: $out" >&2; exit 1
fi
echo "ok: ADVERSARIAL — stale routeTree → exit 1 with remediation message"

# ── Case 3: missing fresh file → exit 2 (loud config error) ──────────────────
set +e
bash "$SCRIPT" "$TMP/committed.ts" "$TMP/does-not-exist.ts" >/dev/null 2>&1; rc=$?
set -e
if [ "$rc" -ne 2 ]; then echo "FAIL: missing file should exit 2, got $rc" >&2; exit 1; fi
echo "ok: missing file → exit 2 (config error)"

# ── Case 4: missing committed file → exit 2 ──────────────────────────────────
set +e
bash "$SCRIPT" "$TMP/nope.ts" "$TMP/fresh.ts" >/dev/null 2>&1; rc=$?
set -e
if [ "$rc" -ne 2 ]; then echo "FAIL: missing committed file should exit 2, got $rc" >&2; exit 1; fi
echo "ok: missing committed file → exit 2"

# ── Case 5: no args → usage / exit 2 ─────────────────────────────────────────
set +e
bash "$SCRIPT" >/dev/null 2>&1; rc=$?
set -e
if [ "$rc" -ne 2 ]; then echo "FAIL: no args should exit 2 (usage), got $rc" >&2; exit 1; fi
echo "ok: no args → exit 2 (usage)"

# ── Git mode ─────────────────────────────────────────────────────────────────
# The two-file cases above pin the compare core, but the gate (`task
# verify:routetree`) runs `--git` mode: REPO_ROOT resolution + `git diff HEAD`.
# Exercise that path against a throwaway repo (ROUTETREE_REPO_ROOT override).
GITREPO="$TMP/gitrepo"
REL="titan-ui/src/routeTree.gen.ts"
mkdir -p "$GITREPO/$(dirname "$REL")"
git -C "$GITREPO" init -q
git -C "$GITREPO" config user.email tester@example.com
git -C "$GITREPO" config user.name tester
printf '%s\n' "$routetree_a" > "$GITREPO/$REL"
git -C "$GITREPO" add -A
git -C "$GITREPO" commit -qm "initial routeTree"

# ── Case 6: git mode, working tree == HEAD → fresh, exit 0 ───────────────────
set +e
out=$(ROUTETREE_REPO_ROOT="$GITREPO" bash "$SCRIPT" --git "$REL" 2>&1); rc=$?
set -e
if [ "$rc" -ne 0 ]; then echo "FAIL: git mode fresh should exit 0, got $rc: $out" >&2; exit 1; fi
echo "ok: git mode — committed == regenerated → exit 0 (fresh)"

# ── Case 7: ADVERSARIAL — git mode, regenerated file drifted → exit 1 ────────
# Simulate `pnpm build` regenerating the file differently from the committed one.
printf '%s\n' "$routetree_drifted" > "$GITREPO/$REL"
set +e
out=$(ROUTETREE_REPO_ROOT="$GITREPO" bash "$SCRIPT" --git "$REL" 2>&1); rc=$?
set -e
if [ "$rc" -ne 1 ]; then echo "FAIL: git mode stale should exit 1, got $rc: $out" >&2; exit 1; fi
if ! printf '%s' "$out" | grep -q "stale"; then echo "FAIL: git mode must say stale. got: $out" >&2; exit 1; fi
if ! printf '%s' "$out" | grep -q "pnpm -C titan-ui build"; then echo "FAIL: git mode must give remediation. got: $out" >&2; exit 1; fi
echo "ok: ADVERSARIAL — git mode regenerated drift → exit 1 with remediation"

# ── Case 8: ADVERSARIAL — staged-blob false-green guard (the HEAD fix) ───────
# This is the exact bug the review flagged: stage a blob matching the
# regenerated output while the COMMITTED file stays stale. HEAD is still the
# stale routetree_a (initial commit); we stage the regenerated (drifted) blob
# so index == regenerated. A bare `git diff` (vs index) would see no diff and
# false-green; `git diff HEAD` must still flag the drift because HEAD is stale.
git -C "$GITREPO" reset -q --hard HEAD            # working tree + index back to stale HEAD
printf '%s\n' "$routetree_drifted" > "$GITREPO/$REL"  # regenerated output (the truth)
git -C "$GITREPO" add "$REL"                      # stage the regenerated blob → index == regenerated
set +e
out=$(ROUTETREE_REPO_ROOT="$GITREPO" bash "$SCRIPT" --git "$REL" 2>&1); rc=$?
set -e
if [ "$rc" -ne 1 ]; then
  echo "FAIL: staged-blob case must still detect stale HEAD (exit 1), got $rc: $out" >&2; exit 1
fi
echo "ok: ADVERSARIAL — staged regenerated blob still flags stale HEAD (vs-HEAD, not vs-index)"
# reset index so the next case starts clean
git -C "$GITREPO" reset -q --hard HEAD

# ── Case 9: git mode, file missing in working tree → exit 2 (config error) ───
rm -f "$GITREPO/$REL"
set +e
ROUTETREE_REPO_ROOT="$GITREPO" bash "$SCRIPT" --git "$REL" >/dev/null 2>&1; rc=$?
set -e
if [ "$rc" -ne 2 ]; then echo "FAIL: git mode missing file should exit 2, got $rc" >&2; exit 1; fi
echo "ok: git mode — missing working-tree file → exit 2 (config error)"

echo ""
echo "PASS: all check-routetree-fresh.sh cases (two-file + git mode + adversarial stale/staged guards)"
