/*
 * titan-trigger-api — pure-Java trigger SPI extracted from titan-server (design/50).
 *
 * Production code depends on JDK + ANTLR (for the vendored cron grammar) +
 * Jackson (the codec/state serialisation contract) + SpotBugs annotations. No Quarkus, no
 * CDI, no JDBI — those wirings stay on the titan-server side, behind the SPIs declared here.
 *
 * Mirrors the titan-step-api ↔ titan-worker split: pure SPI here, framework wiring there.
 */

plugins {
    id("titan.java-library")
}

group = "io.adaptiq.titan"
version = "1.0.0-rc1"

dependencies {
    // The vendored cron grammar (see attribution headers in cron/internal/)
    // is generated by ANTLR — runtime only at build time, transitive consumers don't see it.
    api(libs.antlr.runtime)
    // Trigger codec + state nodes are JsonNode/ObjectNode — Jackson is part of the SPI contract.
    api(libs.jackson.databind)
    implementation(libs.spotbugs.annotations)

    testImplementation(libs.junit.jupiter)
}
